### ISSUE TITLE
rename method recreate.rake#execute

### ISSUE THREAD

**Issue by yasirazgar** [suus-io/rls_rails#14]
The method [execute](https://github.com/suus-io/rls_rails/blob/master/lib/rls_rails/tasks/recreate.rake#L31) defined in recreate.rake seems to conflicting with rails database statement's [execute method](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L120).

**Comment by sbiastoch** [comment]
#15 is now merged, thanks for the PR!
